FROM ingo/ros-groovy-base:12.04
MAINTAINER Ingo Lütkebohle <ingo.luetkebohle@ipvs.uni-stuttgart.de>
RUN apt-get -y install vim binutils pkg-config x11vnc xvfb ros-groovy-object-recognition-capture



