FROM groovy-base:12.04-0.2
MAINTAINER Ingo Lütkebohle <ingo.luetkebohle@ipvs.uni-stuttgart.de>
# this will pull in not just ros, but a whole bunch of X dependencies also
RUN apt-get -y install ros-groovy-desktop binutils pkg-config x11vnc mesa-utils libgtk2.0-0 twm xpra

